### ISSUE TITLE
[BSEP-107] Create knowledge base engine

### ISSUE THREAD

**Issue by drmarjanovic** [dmarjanovic94/bsep-siep#21]
## Info
Define rules using **Drools rules engine** based on **project alarms**.

## TODO
- [x] Get real rules from database and create rules engine which will evaluate rules
- [x] Enable saving of triggered alarm
- [x] Extend alarm-definition model with message that should be displayed in alarm
- [x] Define MultiRule and its HATEOAS
- [x] Create logic for multi-log rules 
- [x] Extend alarm to contain all logs that triggered it
