### ISSUE TITLE
[BSEP-108] Create filter support

### ISSUE THREAD

**Issue by drmarjanovic** [dmarjanovic94/bsep-siep#22]
## Info
Create **JSON API** filter support for all needed entities.

## Subtasks
- [ ] Create _filter_ for `Alarms`
- [x] Create _filter_ for `Logs`
- [ ] Create _filter_ for `Projects`
