### ISSUE TITLE
[BSEP-101] Initial service setup

### ISSUE THREAD

**Issue by stkeky** [dmarjanovic94/bsep-siep#3]
## Info
Create fundamentals for main service application.

## Subtasks
- [x] Setup initial Spring project. 
- [x] Include necessary dependencies. 
- [x] Add docker-compose for services.
- [ ] Additional configuration
