### ISSUE TITLE
[BSEP-118] Email support

### ISSUE THREAD

**Issue by stkeky** [dmarjanovic94/bsep-siep#61]
## Info
Support notifications and verification via email.

### Subtasks
- [x] Send **agent's** `licence` key to **User**.
- [ ] **Notify** when user is added as **collaborator**
- [ ] **Notify** operators about **raised alarm**
- [ ] Create two factor authentication with another field which represents **code**
