### ISSUE TITLE
[BSEP-403] Enable firewall and system logs

### ISSUE THREAD

**Issue by bojanbla** [dmarjanovic94/bsep-siep#88]
## Info

**TODO**:

- [x] Read firewall logs
- [x] Read system logs
- [x] Adapt configuration with service
